### ISSUE TITLE
Plugin fails with "Incompatible Export Type"

### ISSUE THREAD

**Issue by sam-goodwin** [swc-project/register#24]
I followed the instructions for creating a new plugin - https://swc.rs/docs/plugin/ecmascript/getting-started.

1. Ran `swc plugin new`
```
swc plugin new --target-type wasm32-wasi my-first-plugin
```

2. Built the `.wasm` bundle.
```
cargo build --release --target wasm32-wasi && && cp target/wasm32-wasi/release/my_first_plugin.wasm .
```

3. Checked the `package.json` correctly points as the `.wasm` binary.
```
"main": "my_first_plugin.wasm",
```

4. Installed the `my-first-plugin` package in another NPM package using `file:` references.

```
"my-first-plugin": "file:../plugin/my-first-plugin"
```

5. Configured `.swcrc` to use `my-first-plugin`
```json
{
  "jsc": {
    "experimental": {
      "plugins": [["my-first-plugin", {}]]
    }
  }
}
```

6. Ran `node`.

```
node -r @swc/register t.js
```

I get the following error

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/samgoodwin/workspaces/nodejs-closure-serializer/t.js")'

Caused by:
    Incompatible Export Type', crates/swc/src/plugin.rs:273:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/core/index.js:137
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                        ^

Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/samgoodwin/workspaces/nodejs-closure-serializer/t.js")'

Caused by:
    Incompatible Export Type
    at Compiler.transformSync (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/core/index.js:137:25)
    at Object.transformSync (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/core/index.js:217:21)
    at compile (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/register/lib/node.js:76:22)
    at compileHook (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/register/lib/node.js:91:16)
    at Module._compile (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/pirates/lib/index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.newLoader [as .js] (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'GenericFailure'
}
```

Same problem with `@swc/cli`

```
npx swc ./t.js -o u.js
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("t.js")'

Caused by:
    Incompatible Export Type', crates/swc/src/plugin.rs:273:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("t.js")'

Caused by:
    Incompatible Export Type
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/cli/lib/swc/util.js:113:15)
    at files (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/cli/lib/swc/file.js:173:18)
    at async _default (/Users/samgoodwin/workspaces/nodejs-closure-serializer/node_modules/@swc/cli/lib/swc/file.js:192:9)
```

**Comment by sam-goodwin** [comment]
Found this relevant issue https://github.com/swc-project/swc/issues/4333

**Comment by sam-goodwin** [comment]
> Found this relevant issue [swc-project/swc#4333](https://github.com/swc-project/swc/issues/4333)

Getting this problem when using latest version of all packages ...

**Comment by sam-goodwin** [comment]
> > Found this relevant issue [swc-project/swc#4333](https://github.com/swc-project/swc/issues/4333)
> 
> Getting this problem when using latest version of all packages ...

Turns out this was not true. Had to run `cargo update` in my plugin. Sorry for the noise.
